package main;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.io.IOException;

public class PinBekeroGUI extends javax.swing.JFrame {

    private static int kattDb = 0;
    private static boolean mentve = false;
    private static String pin = "";

    public PinBekeroGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlSzamokHelye = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        chbMutat = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        pnlSzamokHelye.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlSzamokHelye.setLayout(new java.awt.GridLayout(0, 3));

        jButton1.setText("jButton1");
        pnlSzamokHelye.add(jButton1);

        jButton4.setText("jButton4");
        pnlSzamokHelye.add(jButton4);

        jButton3.setText("jButton3");
        pnlSzamokHelye.add(jButton3);

        jButton2.setText("jButton2");
        pnlSzamokHelye.add(jButton2);

        jButton7.setText("jButton7");
        pnlSzamokHelye.add(jButton7);

        jButton6.setText("jButton6");
        pnlSzamokHelye.add(jButton6);

        jButton5.setText("jButton5");
        pnlSzamokHelye.add(jButton5);

        jButton8.setText("jButton8");
        pnlSzamokHelye.add(jButton8);

        jButton9.setText("jButton9");
        pnlSzamokHelye.add(jButton9);

        jButton10.setText("jButton10");
        pnlSzamokHelye.add(jButton10);

        chbMutat.setText("mutat");
        chbMutat.setEnabled(false);
        chbMutat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbMutatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlSzamokHelye, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(chbMutat, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chbMutat)
                    .addComponent(pnlSzamokHelye, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(71, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        for (int i = 0; i < pnlSzamokHelye.getComponentCount(); i++) {
            JButton btn = (JButton) pnlSzamokHelye.getComponent(i);
            btn.setText(i + "");
            btn.setBackground(null); // Alapértelmezett szín visszaállítás
            btn.addActionListener(new SzamGombListener());
        }
    }//GEN-LAST:event_formWindowOpened

    private void chbMutatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbMutatActionPerformed
        if (chbMutat.isSelected()) {
            kiemelPin(true);
        } else {
            kiemelPin(false);
        }
    }//GEN-LAST:event_chbMutatActionPerformed
    private class SzamGombListener implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent e) {
            if (kattDb < 4) {
                kattDb++;
                pin += e.getActionCommand();
            }
            if (kattDb == 4 && !mentve) {
                mentve = true;
                chbMutat.setEnabled(true);
                JOptionPane.showMessageDialog(rootPane, "Pin mentve!");

                // PIN mentése fájlba
                mentPinFajlba(pin);
            }
        }
    }

    private void mentPinFajlba(String pin) {
        Path path = Paths.get("pin.txt");
        try {
            Files.writeString(path, pin);
            System.out.println("PIN sikeresen mentve a fájlba.");
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(rootPane, "Hiba a PIN mentésekor: " + ex.getMessage(), "Hiba", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void kiemelPin(boolean mutat) {
        for (int i = 0; i < pin.length(); i++) {
            int gomb = Integer.parseInt(pin.charAt(i) + "");
            JButton btn = (JButton) pnlSzamokHelye.getComponent(gomb);
            btn.setBackground(mutat ? Color.RED : null);
        }
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PinBekeroGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PinBekeroGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PinBekeroGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PinBekeroGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PinBekeroGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox chbMutat;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JPanel pnlSzamokHelye;
    // End of variables declaration//GEN-END:variables
}
